module.exports = {
  "prettier/prettier": [
    "error",
    {
      printWidth: 120,
    },
  ],
  quotes: [
    "error",
    "double",
    { avoidEscape: true, allowTemplateLiterals: false },
  ],
  "max-len": [
    2,
    {
      code: 120,
      tabWidth: 2,
      ignoreStrings: true,
      ignoreRegExpLiterals: true,
      ignoreComments: true,
      ignoreUrls: true,
      ignoreTemplateLiterals: true,
    },
  ],
  curly: ["error", "all"],
  "no-console": 1,
  "no-multiple-empty-lines": 1,
  "eol-last": 2,
  eqeqeq: 2,
  camelcase: 2,
  "prefer-const": 2,
  "no-nested-ternary": 2,
  "@typescript-eslint/no-unused-vars": 1,
  "@typescript-eslint/explicit-module-boundary-types": 2,
  "@typescript-eslint/no-explicit-any": 2,
  "@typescript-eslint/no-non-null-assertion": 0,
  "react/display-name": 0,
  "react/jsx-filename-extension": ["error", { extensions: [".tsx"] }],
  "react/no-children-prop": 1,
  "react/prop-types": 0,
  "react/no-array-index-key": 2,
  "react/jsx-sort-props": [
    2,
    {
      callbacksLast: true,
      shorthandLast: true,
      ignoreCase: true,
    },
  ],
  "react/function-component-definition": [
    2,
    { namedComponents: "arrow-function" },
  ],
  "react-hooks/rules-of-hooks": 2,
  "react-hooks/exhaustive-deps": 1,
  "no-loops/no-loops": 2,
  "import/no-duplicates": 2,
  "import/no-useless-path-segments": 2,
  "import/no-anonymous-default-export": 2,
};
